@startuml
'https://plantuml.com/class-diagram

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

@startuml
package org.example {

  class Alumno {
    - nombre : String
    - apellido : String
    - edad : Integer
    - sexo : String
    - materiasAprobadas : List<Materia>
  }

  class Materia {
    - nombre : String
    - correlativas : List<Materia>
  }

  class Inscripcion {
    + aprobada(alumno : Alumno, materia : Materia) : boolean
  }

  ' Relaciones
  Alumno "1" o-- "*" Materia : materiasAprobadas
  Materia "1" o-- "*" Materia : correlativas
  Inscripcion --> Alumno
  Inscripcion --> Materia
}
@enduml